spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: amr
    password: amr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: payment-service